all:
		g++ -o Agent1 Agent1.cpp
		g++ -o Agent2 Agent2.cpp
		g++ -o Buyer1 Buyer1.cpp
		g++ -o Buyer2 Buyer2.cpp
		g++ -o Buyer3 Buyer3.cpp
		g++ -o Buyer4 Buyer4.cpp
		g++ -o Buyer5 Buyer5.cpp
		g++ -o SellerA SellerA.cpp
		g++ -o SellerB SellerB.cpp
		g++ -o SellerC SellerC.cpp
		g++ -o SellerD SellerD.cpp


$(phony Agent1): 
		./Agent1

Agent2:
		./Agent2

Buyer1:
		./Buyer1

Buyer2:
		./Buyer2

Buyer3:
		./Buyer3

Buyer4:
		./Buyer4

Buyer5:
		./Buyer5

SellerA:
		./SellerA

SellerB:
		./SellerB

SellerC:
		./SellerC

SellerD:
		./SellerD


